robot_num: 4
starts:
  - [2, 10]
  - [18, 10]
  - [10, 2]
  - [10, 18]
goals:
  - [18, 10]
  - [2, 10]
  - [10, 18]
  - [10, 2]
robot_radii:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
width: 20
height: 20
lambda_factor: 0.5
expand_distances:
  - 2.0
  - 2.0
  - 2.0
  - 2.0
obstacles:
  - type: RectangleObstacle
    x: 4
    y: 4
    width: 8
    height: 8
  - type: RectangleObstacle
    x: 4
    y: 16
    width: 8
    height: 8
  - type: RectangleObstacle
    x: 16
    y: 4
    width: 8
    height: 8
  - type: RectangleObstacle
    x: 16
    y: 16
    width: 8
    height: 8
