robot_num: 5
starts:
  - [2, 2]
  - [2, 6]
  - [2, 10]
  - [2, 14]
  - [2, 18]
goals:
  - [18, 2]
  - [18, 6]
  - [18, 10]
  - [18, 14]
  - [18, 18]
robot_radii:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
width: 20
height: 20
lambda_factor: 0.5
collision_check_type: discrete
expand_distances:
  - 3
  - 3
  - 3
  - 3
  - 3
obstacles: []
